"""initial_schema

Revision ID: 9ce91b621628
Revises: 
Create Date: 2026-02-12 13:12:58.326455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce91b621628'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('location_id', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('scrape_date', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('enriched_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index('idx_ingestion_status', 'ingestion_files', ['status'], unique=False)
    op.create_table('insights_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.String(length=10), nullable=False),
    sa.Column('time_window', sa.String(length=50), nullable=False),
    sa.Column('top_topics', sa.Text(), nullable=True),
    sa.Column('key_drivers', sa.Text(), nullable=True),
    sa.Column('representative_quotes', sa.Text(), nullable=True),
    sa.Column('anomalies', sa.Text(), nullable=True),
    sa.Column('generated_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_cache_location_id'), 'insights_cache', ['location_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('review_id', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=255), nullable=True),
    sa.Column('reviewer_type', sa.String(length=50), nullable=True),
    sa.Column('review_date', sa.String(length=50), nullable=True),
    sa.Column('relative_date', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    op.create_index('idx_reviews_location_date', 'reviews', ['location_id', 'review_date'], unique=False)
    op.create_index(op.f('ix_reviews_location_id'), 'reviews', ['location_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=255), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.review_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    op.create_table('enrichments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=255), nullable=False),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('entities', sa.Text(), nullable=True),
    sa.Column('key_phrases', sa.Text(), nullable=True),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('actionable', sa.Boolean(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.review_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrichments')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_reviews_location_id'), table_name='reviews')
    op.drop_index('idx_reviews_location_date', table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('locations')
    op.drop_index(op.f('ix_insights_cache_location_id'), table_name='insights_cache')
    op.drop_table('insights_cache')
    op.drop_index('idx_ingestion_status', table_name='ingestion_files')
    op.drop_table('ingestion_files')
    # ### end Alembic commands ###
